import React, { useEffect, useState } from "react";
import axios from "axios";
const NewsCard = () => {
  // 607bc642ed834272827558c49edf8b46
  const [news, setnews] = useState({});
  const getNews = async () => {
    const options = {
      method: "GET",
      url: "https://bloomberg-market-and-financial-news.p.rapidapi.com/news/list",
      params: { id: "markets" },
      headers: {
        "X-RapidAPI-Key": "46993aa5e2mshf424e4034124846p139af6jsn063932f3b74a",
        "X-RapidAPI-Host": "bloomberg-market-and-financial-news.p.rapidapi.com",
      },
    };

    try {
      const response = await axios.request(options);
      setnews(response.data.modules[0].stories[0]);
    } catch (error) {
      console.error(error);
    }
  };

  useEffect(() => {
    getNews();
  }, []);
  console.log(news);

  const publisheddate = news?.publishedAt?.split("T0");
  if (publisheddate) {
    var publishedtime = publisheddate[1]?.slice(0, -4);
  }

  return (
    <>
      {news ? (
        <div className="news-container">
          <div
            className="news-bg"
            style={{ backgroundImage: `url(${news.image})` }}
          >
            <img src={news.image} width={350} alt="" className="news-img" />
            <div className="title-bg-news">{news.title}</div>
          </div>
          <div className="news-content">{news.autoGeneratedSummary}</div>{" "}
        </div>
      ) : (
        <div> Loading</div>
      )}
    </>
  );
};

export default NewsCard;
